name: CI pipline

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    name: checkout
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"
      - name: install dependencies
        run: pip install -r requirements-dev.txt

      - name: runnng isort
      - run: isort --check only .

      - name: runnng flake8
      - run: flake8 --max-line-length=20 .



